[workspace]
members = [
  "services/gateway-service",
  "services/order-service",
  "services/product-service",
  "services/recommender-service",
  "services/review-service",
  "services/user-service",
  "services/docs-service"
]
